### ISSUE TITLE
Thin segments appear jagged

### ISSUE THREAD

**Issue by nebspetrovic** [brigade/react-simple-pie-chart#1]
![screen shot 2015-04-25 at 3 50 54 pm](https://cloud.githubusercontent.com/assets/2637098/7335238/2a183a50-eb66-11e4-9bd3-9b9453546783.png)

**Comment by nebspetrovic** [comment]
I accidentally linked the wrong commit to this issue. This is the commit that fixes it: https://github.com/nebspetrovic/react-simple-pie-chart/commit/546194b0a1e674214f5d4a08c464a3858a97aafc

**Comment by lencioni** [comment]
Thanks for the fixes!
