### ISSUE TITLE
Don't Require React

### ISSUE THREAD

**Issue by ericelliott** [brigade/react-simple-pie-chart#3]
Hey, did you know that requiring React can cause multiple instances of React in the same app? Possibly multiple versions? And that multiple React instances is a common source of bugs?

Try exporting a factory, instead, and take React as an injected parameter. The technique is demonstrated here in [react-stampit](https://github.com/stampit-org/react-stampit):

> * component is a factory

> This design pattern is optional, but recommended. Component factories are react-stampit's solution for avoiding the often hard to debug problems created by multiple instances of React. Read more about that [here](https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375). By injecting the React library, we are able to guarantee the version and instance of React that a component will receive.

Also, if you implement react-simple-pie-chart as a stamp, you can compose it with any number of mixins or other components like this:

```js
const ComplexPieChart = SimplePieChart(React).compose(ComplexComponent, mixin1, mixin2);

React.render(<ComplexPieChart />);
```

I like to keep things simple, myself, but there are components that can automatically handle state, hook up time travel debugging with Redux, encapsulate component styles, etc... and that can make life for your users even simpler. =)

Cheers!

**Comment by lencioni** [comment]
Thanks for the interest in this component and for the suggestion @ericelliott. react-stampit looks interesting.

However, regarding multiple React instances, I believe that including `react` in `peerDependencies` will prevent this from happening for components like this one--this appears to be the conventional approach. As far as composing it with other mixins or components, it seems easy enough to just create a component that does that. Thanks again for the suggestion, but I don't see enough value in react-stampit for this project.

**Comment by ericelliott** [comment]
[peerDependencies are problematic](https://github.com/npm/npm/issues/6565), and don't do anything about situations where clients load React from a 3rd party CDN for the front end. IMO, injecting React is a much better solution.
